### ISSUE TITLE
Problem with output format

### ISSUE THREAD

**Issue by overthink** [hodadawy/Projects#1]
Hi Hoda,

I was trying to evaluate your solution but there is a problem with the output format. Please make sure each line in the output file is a Result object as described on http://sortable.com/challenge/, i.e.

```
{
  "product_name": String
  "listings": Array[Listing]
}

```

An example line in the output file should look like:

```
{"listings": [{"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Red)"}, {"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Black)"}], "product_name": "Casio_Exilim_EX-FC150"}
```

In your output I see a few issues:
1) Missing closing `}` on each line
2) The value of the `listings` attribute should be an array of listing objects -- yours is currently an array of strings
3) There appears to be escaping issues with `"`

I would recommend using a JSON library and also check some of your output manually with a validation tool like http://jsonlint.com/.

If you are able to fix this up I'd be happy to take another look at your submission.

Thanks!

Mark (from sortable.com)

**Comment by hodadawy** [comment]
Hi Mark,

I just see your message now, I will review the output results file again
and update the github. I will send you an email after I finished it.

Thank a lot,
Hoda

**Comment by hodadawy** [comment]
I updated it, Kindly check the results

**Comment by overthink** [comment]
Hi Hoda.  Thanks for the first fixes.  There is another issue, however.

In your output the value for the `manufacturer` field for each matched listing must be identical to its value  in listings. txt.  In your case it looks like you're outputting the value of the manufacturer field found on the product https://github.com/hodadawy/Projects/blob/a02b7cf06c998a84b687d2dcb75d96f550606a93/match.cpp#L368

It also looks like you might have escaping issues with `"` in your generated JSON file.

Thanks,


Mark

**Comment by hodadawy** [comment]
Hi Mark,

I updated it.

Thanks,
Hoda

**Comment by overthink** [comment]
Hi Hoda.  Looks like there is a file missing:  `g++: error: jsoncpp.cpp: No such file or directory`  Could you add that to the repo please?

We don't normally consider updates/improvements to solutions after they've been initially submitted.  If you want to improve it, that's great, but for scoring purposes I will use the output of the submitted (with bug fixes) version.

**Comment by hodadawy** [comment]
Hi Mark,

I added the missing file jsoncpp.cpp & folder json (includes two files)

Thanks,
Hoda
